import Head from "next/head";
import Transform from "../components/Transform";
import Video from "../components/Video";
import Gallery from "../components/Gallery";
import Valores from "../components/Valores";
import SimpleMap from "../components/SimpleMap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sousas Midia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-1.svg" />
      </Head>
     <Transform />
      <Video />
      <Gallery />
      <Valores />
      <SimpleMap />
    </div>
  );
}
