import Head from "next/head";
import Hero from "../components/Hero";
import BasicPlan from "../components/BasicPlan";
import IntermediatePlan from "../components/IntermediatePlan";
import Solutions from "../components/Solutions";
import AllPlans from "../components/AllPlans";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Web Makers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-1.png" />
      </Head>
      <Hero />
     
     
      <Solutions />
      <AllPlans />
    </div>
  );
}
