import React from "react";
import Site from "../components/Site";
import Head from "next/head";

const site = () => {
  return (
    <div>
      <Head>
        <title>Site / Sousas Midia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-1.svg" />
      </Head>
      <Site />
    </div>
  );
};

export default site;
