import React from 'react'
import SocialMedia from '../components/SocialMedia'
import Head from 'next/head'

const socialmedia = () => {
  return (
    <div>
    <Head>
        <title>Social media / Sousas Midia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-1.svg" />
      </Head>
      <SocialMedia />
    </div>
  )
}

export default socialmedia
